apiVersion: v1
kind: Service
metadata:
  name: pixtools-api
  namespace: pixtools
spec:
  selector:
    app: pixtools-api
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000

