apiVersion: v1
kind: ConfigMap
metadata:
  name: pixtools-config
  namespace: pixtools
data:
  AWS_REGION: "us-east-1"
  IDEMPOTENCY_TTL_SECONDS: "86400"
  WEBHOOK_CB_FAIL_THRESHOLD: "5"
  WEBHOOK_CB_RESET_TIMEOUT: "60"
  MAX_UPLOAD_BYTES: "10485760"
  MAX_IMAGE_WIDTH: "1920"
  MAX_IMAGE_HEIGHT: "1080"
  PRESIGNED_URL_EXPIRY_SECONDS: "86400"
  JOB_RETENTION_HOURS: "24"
  S3_RETENTION_DAYS: "1"

