apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixtools-worker-standard
  namespace: pixtools
  labels:
    app: pixtools-worker-standard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pixtools-worker-standard
  template:
    metadata:
      labels:
        app: pixtools-worker-standard
    spec:
      nodeSelector:
        pixtools-workload-app: "true"
      imagePullSecrets:
        - name: ecr-pull
      containers:
        - name: worker-standard
          image: __WORKER_IMAGE__
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - app.tasks.celery_app
            - worker
            - -Q
            - default_queue
            - --concurrency=6
            - --loglevel=info
          envFrom:
            - configMapRef:
                name: pixtools-config
            - secretRef:
                name: pixtools-runtime
          resources:
            requests:
              cpu: "250m"
              memory: "320Mi"
            limits:
              cpu: "900m"
              memory: "768Mi"
